blogRails/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index'
  resources :posts

  post '/posts/:id', to: 'posts#comment', as: 'comment'
  get '/upload', to: 'posts#new', as: 'upload'

  devise_for :users
end

blogRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogRails/app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

blogRails/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

blogRails/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments
end

blogRails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def is_admin?
    true
  end
end

blogRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blogRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
    # .search(params)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to root_path
    else
      redirect_to upload_path
    end
  end

  def comment
    # com = Comment.new(
    #   name: params[:name],
    #   email: params[:email],
    #   content: params[:content]
    # ).call
    #
    # raise com.inspect
    # if com.save
    #   render json: {success: false, errors: message.errors}.to_json, status: 422
    # else
    #   redirect_to post_path(params[:id])
    # end

    redirect_to post_path(params[:id])
  end

private
  def post_params
    params.required(:post).permit(:title, :category_id, :content).merge(user_id: current_user.id)
  end

end

blogRails/app/helpers/application_helper.rb
module ApplicationHelper
end

blogRails/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Blog
    = csrf_meta_tags
    %link{href: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u", crossorigin: "anonymous"}
    %link{href: "https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/paper/bootstrap.min.css", rel: "stylesheet", integrity: "sha384-awusxf8AUojygHf2+joICySzB780jVvQaVCAt1clU3QsyAitLGul28Qxb2r1e5g+", crossorigin: "anonymous"}
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .header
      = render partial: '/shared/header'
    .container.content{style: 'margin-top: 100px'}
      = yield


%script{src: "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js", integrity: "sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa", crossorigin: "anonymous"}

blogRails/app/views/posts/index.html.haml
%div
  %ul
    - @posts.each do |post|
      %li
        %a{href: post_path(post.id)}
          = post.title

blogRails/app/views/posts/new.html.haml
.row
  .col-xs-8.col-xs-offset-2
    %h3= 'Nouveau Post'
-# - if @post.errors.any?
-#   .row
-#     .col-xs-8.col-xs-offset-2.errors
-#       %h2
-#         = pluralize(@listing.errors.count, "error")
-#         = t('errors', count: @post.errors.count)
-#       %ul
-#         - @post.errors.full_messages.each do |msg|
-#           %li= msg
.row
  .col-xs-8.col-xs-offset-2
    = form_for @post, class: 'form', html: {multipart: true} do |f|
      .form-group
        = f.label :title, class: 'form-label required'
        = f.text_field :title, class: 'form-control'
      .form-group
        = f.label :category_id, class: 'form-label required'
        = f.collection_select :category_id, Category.all, :id, :name, {}, {class: 'form-control'}

      .form-group
        = f.label :content, class: 'form-label required'
        = f.text_field :content, class: 'form-control'

      .form-group
        -# %span= t('required_field')
        = f.submit "Publier le Post", class: 'btn btn-primary pull-right'

blogRails/app/views/posts/show.html.haml
.row
  .col-xs-12
    %h2= @post.title
    %p= @post.content

  .col-xs-8.col-xs-offset-2
    %h3
      = "Commentaire"

    %p
      - Comment.all.each do |comment|
        -if comment.post_id == @post.id
          %div
            = comment.name
          %div
            = comment.email
          %div
            = comment.content

    .col-xs-12
      = form_for comment_path, class: 'form', html: {multipart: true} do |f|
        .form-group
          = f.label :name, class: 'form-label required'
          = f.text_field :name, class: 'form-control'
        .form-group
          = f.label :email, class: 'form-label required'
          = f.email_field :email, class: 'form-control'
        .form-group
          = f.label :content, class: 'form-label required'
          = f.text_field :content, class: 'form-control'

        .form-group
          = f.submit "Publier le Commentaire", class: 'btn btn-primary pull-right'

blogRails/app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path}
        = 'Blog'

      %form.navbar-form.navbar-left{:role => "search"}
        = form_tag posts_path, method: :get, class:'form form-hroizontal'  do
          .form-group
            .col-xs-10
              = text_field_tag 'keywords', nil, class: 'form-control', placeholder: "search"

      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{href: upload_path} Ajouter un Post
          %li
            %a.fa.fa-sign-out{href: destroy_user_session_path}

      - else
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{href: new_user_session_path} Connexion

blogRails/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>